<?php
namespace App\Http\Controllers\Comercial;
use App\Domains\Comercial\LiveSales\Actions\AgregarProductoLiveAction;use App\Domains\Comercial\LiveSales\Actions\ActualizarSesionLiveAction;use App\Domains\Comercial\LiveSales\Actions\CambiarEstadoSesionLiveAction;use App\Domains\Comercial\LiveSales\Actions\ConvertirInteraccionLiveEnLeadAction;use App\Domains\Comercial\LiveSales\Actions\ConvertirInteraccionLiveEnPedidoAction;use App\Domains\Comercial\LiveSales\Actions\CrearSesionLiveAction;use App\Domains\Comercial\LiveSales\Actions\RegistrarInteraccionLiveAction;use App\Domains\Comercial\LiveSales\Enums\EstadoInteraccionLiveEnum;use App\Domains\Comercial\LiveSales\Enums\EstadoSesionLiveEnum;use App\Http\Controllers\Controller;use App\Http\Requests\LiveSales\StoreInteraccionLiveRequest;use App\Http\Requests\LiveSales\StoreProductoLiveRequest;use App\Http\Requests\LiveSales\StoreSesionLiveRequest;use App\Http\Requests\LiveSales\UpdateSesionLiveRequest;use App\Models\CanalVenta;use App\Models\InteraccionLive;use App\Models\Producto;use App\Models\SesionLive;use Inertia\Inertia;
class LiveSalesController extends Controller {
public function index(){ $this->authorize('pedidos.ver'); return Inertia::render('LiveSales/Index',['sesiones'=>SesionLive::with('canalVenta')->latest()->get()]);}
public function create(){ $this->authorize('pedidos.crear'); return Inertia::render('LiveSales/Create',['canales'=>CanalVenta::all(),'estados'=>array_column(EstadoSesionLiveEnum::cases(),'value')]);}
public function store(StoreSesionLiveRequest $r,CrearSesionLiveAction $a){$data=$r->validated();$data['cod_usuario_responsable']=$data['cod_usuario_responsable']??auth()->id();$a->execute($data);return redirect()->route('live-sales.index');}
public function show(SesionLive $live_sale){$this->authorize('pedidos.ver'); return Inertia::render('LiveSales/Show',['sesion'=>$live_sale->load(['canalVenta','productosLive.producto','interaccionesLive.producto']),'productos'=>Producto::all(),'estadosInteraccion'=>array_column(EstadoInteraccionLiveEnum::cases(),'value')]);}
public function edit(SesionLive $live_sale){$this->authorize('pedidos.editar'); return Inertia::render('LiveSales/Edit',['sesion'=>$live_sale,'canales'=>CanalVenta::all(),'estados'=>array_column(EstadoSesionLiveEnum::cases(),'value')]);}
public function update(UpdateSesionLiveRequest $r,SesionLive $live_sale,ActualizarSesionLiveAction $a){$a->execute($live_sale,$r->validated());return redirect()->route('live-sales.show',$live_sale);} 
public function cambiarEstado(SesionLive $live_sale,CambiarEstadoSesionLiveAction $a){$this->authorize('pedidos.editar');$a->execute($live_sale,request('estado_ses'));return back();}
public function agregarProducto(StoreProductoLiveRequest $r,SesionLive $live_sale,AgregarProductoLiveAction $a){$a->execute([...$r->validated(),'cod_sesion_live'=>$live_sale->cod_sesion_live]);return back();}
public function registrarInteraccion(StoreInteraccionLiveRequest $r,SesionLive $live_sale,RegistrarInteraccionLiveAction $a){$d=$r->validated();$d['cod_sesion_live']=$live_sale->cod_sesion_live;$d['estado_int']=$d['estado_int']??EstadoInteraccionLiveEnum::NUEVO->value;$d['cod_usuario_responsable']=$d['cod_usuario_responsable']??auth()->id();$a->execute($live_sale,$d);return back();}
public function convertirLead(InteraccionLive $interaccion_live,ConvertirInteraccionLiveEnLeadAction $a){$this->authorize('leads.crear');$a->execute($interaccion_live);return back();}
public function convertirPedido(InteraccionLive $interaccion_live,ConvertirInteraccionLiveEnPedidoAction $a){$this->authorize('pedidos.crear');$a->execute($interaccion_live);return back();}
}
